
services:
  db:
    image: postgres:15
    container_name: restaurant-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: restaurant-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_g6fuO4ihUKek@ep-winter-lake-atw1zd2c-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - PORT=3001
      - JWT_SECRET=supersecretkey_anticrowd_restaurant_app_2026
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    restart: always
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  pgdata:
